//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.OpenWaitService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="OpenWaitService.IServiceOpenWait")]
    public interface IServiceOpenWait {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceOpenWait/SetRecordProcessRequest", ReplyAction="http://tempuri.org/IServiceOpenWait/SetRecordProcessRequestResponse")]
        void SetRecordProcessRequest(System.Guid wwfId, string bookmark);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceOpenWait/SetRecordProcessRequest", ReplyAction="http://tempuri.org/IServiceOpenWait/SetRecordProcessRequestResponse")]
        System.Threading.Tasks.Task SetRecordProcessRequestAsync(System.Guid wwfId, string bookmark);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServiceOpenWaitChannel : WebApplication1.OpenWaitService.IServiceOpenWait, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServiceOpenWaitClient : System.ServiceModel.ClientBase<WebApplication1.OpenWaitService.IServiceOpenWait>, WebApplication1.OpenWaitService.IServiceOpenWait {
        
        public ServiceOpenWaitClient() {
        }
        
        public ServiceOpenWaitClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServiceOpenWaitClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceOpenWaitClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceOpenWaitClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void SetRecordProcessRequest(System.Guid wwfId, string bookmark) {
            base.Channel.SetRecordProcessRequest(wwfId, bookmark);
        }
        
        public System.Threading.Tasks.Task SetRecordProcessRequestAsync(System.Guid wwfId, string bookmark) {
            return base.Channel.SetRecordProcessRequestAsync(wwfId, bookmark);
        }
    }
}
